version: '3.8'

services:
  postgres:
    container_name: postgres_qtask
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak_qtask
    image: quay.io/keycloak/keycloak:26.2.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local